### ISSUE TITLE
Crash during VM change

### ISSUE THREAD

**Issue by htj** [nutanix/terraform-provider-nutanix#132] opened 2018-06-07 06:31 UTC
Hi, had a crash yesterday. I cannot recall the exact conditions (I went home straight after), but hopefully the crash log helps. Looks like a null dereference.

```
htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)
nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: Refreshing state... (ID: ce43057d-7448-4d3c-8759-1b2fada49d95)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net
      disk_list.#:                                    "0" => "1"
      disk_list.0.data_source_reference.#:            "0" => "1"
      disk_list.0.data_source_reference.0.kind:       "" => "image"
      disk_list.0.data_source_reference.0.name:       "" => "ubuntu-16.04-server-cloudimg-amd64-disk1-20180509-console-fix.img"
      disk_list.0.data_source_reference.0.uuid:       "" => "058e0f7c-a294-4730-a355-0326f6127898"
      disk_list.0.device_properties.#:                "0" => "1"
      disk_list.0.device_properties.0.device_type:    "" => "DISK"
      disk_list.0.device_properties.0.disk_address.#: "" => <computed>
      disk_list.0.disk_size_mib:                      "" => "10000"
      disk_list.0.volume_group_reference.#:           "" => <computed>
      guest_customization_cloud_init.%:               "2" => "1"
      guest_customization_cloud_init.meta_data:       "" => ""
      nic_list.#:                                     "0" => "2"
      nic_list.0.ip_endpoint_list.#:                  "" => <computed>
      nic_list.0.network_function_chain_reference.%:  "" => <computed>
      nic_list.0.subnet_reference.%:                  "0" => "2"
      nic_list.0.subnet_reference.kind:               "" => "subnet"
      nic_list.0.subnet_reference.uuid:               "" => "409dfe87-8c94-469b-ae6a-23f457ae586f"
      nic_list.1.ip_endpoint_list.#:                  "" => <computed>
      nic_list.1.network_function_chain_reference.%:  "" => <computed>
      nic_list.1.subnet_reference.%:                  "0" => "2"
      nic_list.1.subnet_reference.kind:               "" => "subnet"
      nic_list.1.subnet_reference.uuid:               "" => "5a3253fc-dec0-4fdd-b9a4-b532358ac2e6"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: ^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...


Error: Error asking for approval: interrupted


htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: Refreshing state... (ID: ce43057d-7448-4d3c-8759-1b2fada49d95)

Error: Error refreshing state: 1 error(s) occurred:

* nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: 1 error(s) occurred:

* nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: unexpected EOF


panic: runtime error: invalid memory address or nil pointer dereference
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x18236ef]
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix:
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: goroutine 98 [running]:
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: github.com/terraform-providers/terraform-provider-nutanix/nutanix.resourceNutanixVirtualMachineRead(0xc42021fc00, 0x18aca40, 0xc4201a4768, 0xc42021fc00, 0x0)
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: 	/Users/htj/go/src/github.com/terraform-providers/terraform-provider-nutanix/nutanix/resource_nutanix_virtual_machine.go:132 +0x10f
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4205c83f0, 0xc4200b28c0, 0x18aca40, 0xc4201a4768, 0xc4205f0a48, 0x10bc401, 0x18a46c0)
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: 	/Users/htj/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:354 +0x167
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4205f8000, 0xc4200b2870, 0xc4200b28c0, 0xc420063ba8, 0x13c8e94, 0x1fff8a0)
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: 	/Users/htj/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4205a1400, 0xc420308780, 0xc420308850, 0x0, 0x0)
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: 	/Users/htj/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: reflect.Value.call(0xc420088ba0, 0xc42019a0a0, 0x13, 0x1a3cb23, 0x4, 0xc420063f18, 0x3, 0x3, 0xc4203c8d80, 0xc42039bee8, ...)
2018-06-06T16:07:09.457+0200 [DEBUG] plugin.terraform-provider-nutanix: 	/usr/local/Cellar/go/1.10.2/libexec/src/reflect/value.go:447 +0x969
2018-06-06T16:07:09.458+0200 [DEBUG] plugin.terraform-provider-nutanix: reflect.Value.Call(0xc420088ba0, 0xc42019a0a0, 0x13, 0xc42039bf18, 0x3, 0x3, 0xc4202d31a0, 0xc400000002, 0x0)
2018-06-06T16:07:09.458+0200 [DEBUG] plugin.terraform-provider-nutanix: 	/usr/local/Cellar/go/1.10.2/libexec/src/reflect/value.go:308 +0xa4
2018-06-06T16:07:09.458+0200 [DEBUG] plugin.terraform-provider-nutanix: net/rpc.(*service).call(0xc4201940c0, 0xc4204b20f0, 0xc420530030, 0xc420530040, 0xc420382500, 0xc4204c6500, 0x18a4680, 0xc420308780, 0x16, 0x18a46c0, ...)
2018-06-06T16:07:09.458+0200 [DEBUG] plugin.terraform-provider-nutanix: 	/usr/local/Cellar/go/1.10.2/libexec/src/net/rpc/server.go:384 +0x14e
2018-06-06T16:07:09.458+0200 [DEBUG] plugin.terraform-provider-nutanix: created by net/rpc.(*Server).ServeCodec
2018-06-06T16:07:09.458+0200 [DEBUG] plugin.terraform-provider-nutanix: 	/usr/local/Cellar/go/1.10.2/libexec/src/net/rpc/server.go:480 +0x43a
2018/06/06 16:07:09 [ERROR] root: eval: *terraform.EvalRefresh, err: nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: unexpected EOF
2018/06/06 16:07:09 [ERROR] root: eval: *terraform.EvalSequence, err: nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: unexpected EOF
2018/06/06 16:07:09 [TRACE] [walkRefresh] Exiting eval tree: nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net
2018/06/06 16:07:09 [TRACE] dag/walk: upstream errored, not walking "provider.nutanix (close)"
2018-06-06T16:07:09.462+0200 [DEBUG] plugin: plugin process exited: path=/Users/htj/projects/ndn-iaas/tfntnx/.terraform/plugins/darwin_amd64/terraform-provider-nutanix
2018/06/06 16:07:09 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-06-06T16:07:09.462+0200 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Gist crash log https://gist.github.com/htj/f330b9d8ecae8bbe035a7f536d89efd2

**Comment by Crizstian** [comment] 2018-06-07 15:16
Hello @htj could you please pass me the steps to reproduce this, because i am not able to make it crash.

**Comment by htj** [comment] 2018-06-08 09:01
Hi. As I wrote, I cannot recall the exact conditions.

Looking at stack trace gives a pretty good hint though:

Line 132 in nutanix/resource_nutanix_virtual_machine.go
```
    n := setNicList(resp.Status.Resources.NicList)
```

I'm betting that Status, Resources, or NicList is null.

**Comment by Crizstian** [comment] 2018-06-08 17:57
Hey @htj  Status and Resources won't be null ever, cause the API always responds this, if NicList is null, we already handle that scenario, so I will close this issue, and if you get this error again, please feel free to open it again, and share your configuration to be able to reproduce your steps.

**Closed by Crizstian** 2018-06-08 17:57 UTC
