### ISSUE TITLE
Error when re-applying a plan

### ISSUE THREAD

**Issue by ryanhayesntnx** [nutanix/terraform-provider-nutanix#41] opened 2019-03-25 22:19 UTC
**nutanix_virtual_machine.WD.0: internal error: cannot shut down the VM with UUID(a12dce4a-b1a4-4ad7-b581-1810aea2aa21): error updating Virtual Machine UUID(a12dce4a-b1a4-4ad7-b581-1810aea2aa21): error: {
  "api_version": "3.1",
  "code": 422,
  "message_list": [
    {
      "message": "Must specify NIC is_connected during update.",
      "reason": "INVALID_REQUEST"
    }
  ],
  "state": "ERROR"Describe the bug**

**Expected behavior**

**Logs**
If you've got any logs/outputs, attach them

**Versions (please complete the following information):**
 - OS that is executing Terraform
 - Terraform
 - Nutanix Cluster (Prism Element / AOS)
 - Nutanix Prism Central
 - Terraform provider version (using posted RC1? Compiling yourself? If so, from Develop or Master, and what commit id?

**Additional context**

**Comment by switchboardOp** [comment] 2019-05-17 20:03
This is a duplicate of #33

**Comment by marinsalinas** [comment] 2019-05-20 18:12
Closed by duplicate issue on #33

**Closed as completed by marinsalinas** 2019-05-20 18:12 UTC
