### ISSUE TITLE
Error when refreshing image state

### ISSUE THREAD

**Issue by htj** [nutanix/terraform-provider-nutanix#133] opened 2018-06-07 08:19 UTC
After a failed image creation (see #48), terraform now consistenly fails with this message:

```
htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_image.alpine-standard-3_7_0-x86_64: Refreshing state... (ID: cc3b0505-f8ba-4a50-bf8b-1115b709edcd)
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)

Error: Error refreshing state: 1 error(s) occurred:

* nutanix_image.alpine-standard-3_7_0-x86_64: nutanix_image.alpine-standard-3_7_0-x86_64: Error: {
  "message_list": [
    {
      "message": "Fanout failed: Remote endpoint 000566ab-34b0-0fef-3f9b-0cc47ac5db50 - Could not access the URL, please check the URL and make sure the hostname is resolvable",
      "reason": "INTERNAL_ERROR"
    }
  ],
  "state": "ERROR"
}
```

Which means I cannot get anywhere.

**Comment by thetonymaster** [comment] 2018-06-07 17:52
Hey @htj how can I reproduce this? What where the steps that caused this error? in #134 I am destroying the resource if the upload fails, but I can't reproduce this specific error message.

**Comment by htj** [comment] 2018-06-08 08:58
I think it was:

1. upload image from local image. Which fails for some reason
2. terraform apply

**Comment by JonKohler** [comment] 2018-07-05 03:11
@htj - can you retry this with the RC1 code that is posted under releases?

**Comment by htj** [comment] 2018-07-10 12:11
Still getting this.

Full terminal output follows:

```
htj@iridium:~/projects/ndn-iaas/tfntnx$ cat alpine.tf

resource "nutanix_image" "alpine-standard-3_7_0-x86_64" {

  name        = "alpine-standard-3.7.0-x86_64"
  description = "alpine-standard-3.7.0-x86_64"
  source_uri  = "alpine-standard-3.7.0-x86_64.iso"

}

htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)
nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: Refreshing state... (ID: b80c0f1a-40ca-4630-932f-38ab16baf2c3)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + nutanix_image.alpine-standard-3_7_0-x86_64
      id:                            <computed>
      api_version:                   <computed>
      architecture:                  <computed>
      availability_zone_reference.%: <computed>
      categories.#:                  <computed>
      checksum.%:                    <computed>
      cluster_reference.%:           <computed>
      description:                   "alpine-standard-3.7.0-x86_64"
      image_type:                    <computed>
      metadata.%:                    <computed>
      name:                          "alpine-standard-3.7.0-x86_64"
      owner_reference.%:             <computed>
      retrieval_uri_list.#:          <computed>
      size_bytes:                    <computed>
      source_path:                   <computed>
      source_uri:                    "alpine-standard-3.7.0-x86_64.iso"
      state:                         <computed>
      version.%:                     <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

nutanix_image.alpine-standard-3_7_0-x86_64: Creating...
  api_version:                   "" => "<computed>"
  architecture:                  "" => "<computed>"
  availability_zone_reference.%: "" => "<computed>"
  categories.#:                  "" => "<computed>"
  checksum.%:                    "" => "<computed>"
  cluster_reference.%:           "" => "<computed>"
  description:                   "" => "alpine-standard-3.7.0-x86_64"
  image_type:                    "" => "<computed>"
  metadata.%:                    "" => "<computed>"
  name:                          "" => "alpine-standard-3.7.0-x86_64"
  owner_reference.%:             "" => "<computed>"
  retrieval_uri_list.#:          "" => "<computed>"
  size_bytes:                    "" => "<computed>"
  source_path:                   "" => "<computed>"
  source_uri:                    "" => "alpine-standard-3.7.0-x86_64.iso"
  state:                         "" => "<computed>"
  version.%:                     "" => "<computed>"
nutanix_image.alpine-standard-3_7_0-x86_64: Still creating... (10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* nutanix_image.alpine-standard-3_7_0-x86_64: 1 error(s) occurred:

* nutanix_image.alpine-standard-3_7_0-x86_64: error: {
  "message_list": [
    {
      "message": "Fanout failed: Remote endpoint 000566ab-34b0-0fef-3f9b-0cc47ac5db50 - Could not access the URL, please check the URL and make sure the hostname is resolvable",
      "reason": "INTERNAL_ERROR"
    }
  ],
  "state": "ERROR"
}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_image.alpine-standard-3_7_0-x86_64: Refreshing state... (ID: 446a846f-ea83-4066-94b6-cefcff0cc1bd)
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)
nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: Refreshing state... (ID: b80c0f1a-40ca-4630-932f-38ab16baf2c3)

Error: Error refreshing state: 1 error(s) occurred:

* nutanix_image.alpine-standard-3_7_0-x86_64: 1 error(s) occurred:

* nutanix_image.alpine-standard-3_7_0-x86_64: nutanix_image.alpine-standard-3_7_0-x86_64: error: {
  "message_list": [
    {
      "message": "Fanout failed: Remote endpoint 000566ab-34b0-0fef-3f9b-0cc47ac5db50 - Could not access the URL, please check the URL and make sure the hostname is resolvable",
      "reason": "INTERNAL_ERROR"
    }
  ],
  "state": "ERROR"
}


htj@iridium:~/projects/ndn-iaas/tfntnx$ terraform apply
nutanix_subnet.vlan66: Refreshing state... (ID: 409dfe87-8c94-469b-ae6a-23f457ae586f)
nutanix_subnet.vlan67: Refreshing state... (ID: 5a3253fc-dec0-4fdd-b9a4-b532358ac2e6)
nutanix_image.alpine-standard-3_7_0-x86_64: Refreshing state... (ID: 446a846f-ea83-4066-94b6-cefcff0cc1bd)
nutanix_virtual_machine.terraform-test-se-tug-ntp01_nordu_net: Refreshing state... (ID: b80c0f1a-40ca-4630-932f-38ab16baf2c3)

Error: Error refreshing state: 1 error(s) occurred:

* nutanix_image.alpine-standard-3_7_0-x86_64: 1 error(s) occurred:

* nutanix_image.alpine-standard-3_7_0-x86_64: nutanix_image.alpine-standard-3_7_0-x86_64: error: {
  "message_list": [
    {
      "message": "Fanout failed: Remote endpoint 000566ab-34b0-0fef-3f9b-0cc47ac5db50 - Could not access the URL, please check the URL and make sure the hostname is resolvable",
      "reason": "INTERNAL_ERROR"
    }
  ],
  "state": "ERROR"
}
```

It looks like this occurs when doing a resource refresh and an image resource doesn't exists, even though terraform expects it to.

**Comment by thetonymaster** [comment] 2018-07-12 19:39
Hey, as  stated on the documentation the correct attribute to upload an image is `source_path` https://github.com/nutanix/terraform-provider-nutanix/blob/develop/website/docs/r/image.html.markdown

@JonKohler I did not add validation here because of the regex for an URL can get a little bit nasty, I suppose the correct way would be checking if the URI field has a local address (it might be easy to do with a stat call). URL's, on the other hand, can be wildly varied and I don't know if it's worth maintaining it.

**Comment by htj** [comment] 2018-07-13 08:23
With TF_LOG=debug:

```
2018/07/13 10:19:48 [INFO] terraform: building graph: GraphTypeApply
, NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "image_type":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "retrieval_uri_list.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "cluster_reference.%":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "checksum.%":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "size_bytes":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "owner_reference.%":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x2}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
2018/07/13 10:19:48 [DEBUG] Resource state not found for "nutanix_image.alpine-standard-3_7_0-x86_64": nutanix_image.alpine-standard-3_7_0-x86_64
2018/07/13 10:19:48 [DEBUG] ReferenceTransformer: "var.nutanix_server" references: []
2018/07/13 10:19:48 [DEBUG] ReferenceTransformer: "local.kas_lab_cluster" references: []
2018/07/13 10:19:48 [DEBUG] ReferenceTransformer: "nutanix_image.alpine-standard-3_7_0-x86_64" references: []
2018/07/13 10:19:48 [DEBUG] ReferenceTransformer: "provider.nutanix" references: [var.nutanix_user var.nutanix_password var.nutanix_server]
2018/07/13 10:19:48 [DEBUG] ReferenceTransformer: "var.nutanix_user" references: []
2018/07/13 10:19:48 [DEBUG] ReferenceTransformer: "var.nutanix_password" references: []
2018/07/13 10:19:48 [DEBUG] Starting graph walk: walkApply
nutanix_image.alpine-standard-3_7_0-x86_64: Creating...
  api_version:                   "" => "<computed>"
  architecture:                  "" => "<computed>"
  availability_zone_reference.%: "" => "<computed>"
  categories.#:                  "" => "<computed>"
2018-07-13T10:19:48.166+0200 [DEBUG] plugin.terraform-provider-nutanix: 2018/07/13 10:19:48 [DEBUG] Creating Image: alpine-standard-3.7.0-x86_64
2018-07-13T10:19:48.166+0200 [DEBUG] plugin.terraform-provider-nutanix: 2018/07/13 10:19:48 [DEBUG] Get Image Existence : alpine-standard-3.7.0-x86_64
  checksum.%:                    "" => "<computed>"
  cluster_reference.%:           "" => "<computed>"
  description:                   "" => "alpine-standard-3.7.0-x86_64"
  image_type:                    "" => "<computed>"
  metadata.%:                    "" => "<computed>"
  name:                          "" => "alpine-standard-3.7.0-x86_64"
  owner_reference.%:             "" => "<computed>"
  retrieval_uri_list.#:          "" => "<computed>"
  size_bytes:                    "" => "<computed>"
  source_path:                   "" => "alpine-standard-3.7.0-x86_64.iso"
  source_uri:                    "" => "<computed>"
  state:                         "" => "<computed>"
  version.%:                     "" => "<computed>"
2018-07-13T10:19:48.440+0200 [DEBUG] plugin.terraform-provider-nutanix: 2018/07/13 10:19:48 [DEBUG] Waiting for state to become: [COMPLETE]
nutanix_image.alpine-standard-3_7_0-x86_64: Still creating... (10s elapsed)
2018-07-13T10:20:01.297+0200 [DEBUG] plugin.terraform-provider-nutanix: 2018/07/13 10:20:01 [DEBUG] Deleting Image: alpine-standard-3.7.0-x86_64
2018-07-13T10:20:01.413+0200 [DEBUG] plugin.terraform-provider-nutanix: 2018/07/13 10:20:01 [DEBUG] Waiting for state to become: [DELETED]
nutanix_image.alpine-standard-3_7_0-x86_64: Still creating... (20s elapsed)

2018/07/13 10:20:11 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

1 error(s) occurred:

* nutanix_image.alpine-standard-3_7_0-x86_64: 1 error(s) occurred:

* nutanix_image.alpine-standard-3_7_0-x86_64: failed uploading image: unexpected end of JSON input

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


2018-07-13T10:20:11.555+0200 [DEBUG] plugin.terraform-provider-nutanix: 2018/07/13 10:20:11 [ERR] plugin: plugin server: accept unix /var/folders/1_/k486srv9137502150_lq5qcm0000gn/T/plugin019186903: use of closed network connection
2018-07-13T10:20:11.576+0200 [DEBUG] plugin: plugin process exited: path=/Users/htj/projects/ndn-iaas/tfntnx/.terraform/plugins/darwin_amd64/terraform-provider-nutanix
```

Seems a connection is used after it was closed.

**Comment by JonKohler** [comment] 2018-10-02 16:01
@thetonymaster is this fixed with your recent commits?

**Comment by JonKohler** [comment] 2018-10-03 01:11
Should be fixed with Tony's latest commits. We've added more verbosity as well as unit testing for this.

**Closed by JonKohler** 2018-10-03 01:11 UTC
Labels: review

**Comment by htj** [comment] 2018-10-09 11:55
Hi

Just tested with latest git from today and with AHV 5.8.2. Image upload seems to work now. Thanks.
